// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class AdornmentTest : Terminal.Gui.ViewBase.Adornment
    {
        private Terminal.Gui.ViewBase.Adornment TestAdornment = null!;

        private void InitializeComponent()
        {
            TestAdornment = this;
            TestAdornment.Diagnostics = Terminal.Gui.ViewBase.ViewDiagnosticFlags.DrawIndicator;
            TestAdornment.Thickness = Terminal.Gui.Drawing.Thickness.Empty;
        }
    }
}
