// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class AdornmentViewTest : Terminal.Gui.ViewBase.AdornmentView
    {
        private Terminal.Gui.ViewBase.AdornmentView TestAdornmentView = null!;

        private void InitializeComponent()
        {
            TestAdornmentView = this;
            TestAdornmentView.Diagnostics = Terminal.Gui.ViewBase.ViewDiagnosticFlags.DrawIndicator;
        }
    }
}
