// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class AttributePickerTest : Terminal.Gui.Views.AttributePicker
    {
        private Terminal.Gui.Views.AttributePicker AttributePicker1 = null!;

        private void InitializeComponent()
        {
            AttributePicker1 = this;
        }
    }
}
