// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class AttributePickerTest : Terminal.Gui.Views.AttributePicker
    {
        private Terminal.Gui.Views.AttributePicker TestAttributePicker = null!;

        private void InitializeComponent()
        {
            TestAttributePicker = this;
            TestAttributePicker.X = 5;
            TestAttributePicker.Y = 2;
            TestAttributePicker.Width = 30;
            TestAttributePicker.Height = 5;
            TestAttributePicker.SampleText = "Sample";
        }
    }
}
