// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class BarTest : Terminal.Gui.Views.Bar
    {
        private Terminal.Gui.Views.Bar Bar1 = null!;

        private void InitializeComponent()
        {
            Bar1 = this;
            Bar1.X = Pos.Center();
            Bar1.Y = Pos.Center();
        }
    }
}
