// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class BorderTestView : Terminal.Gui.ViewBase.Border
    {
        private Terminal.Gui.ViewBase.Border TestBorder = null!;

        private void InitializeComponent()
        {
            TestBorder = this;
            TestBorder.Diagnostics = Terminal.Gui.ViewBase.ViewDiagnosticFlags.Sample;
            TestBorder.LineStyle = Terminal.Gui.Drawing.LineStyle.Sample;
            TestBorder.Parent = Terminal.Gui.ViewBase.View.Sample;
            TestBorder.Settings = Terminal.Gui.ViewBase.BorderSettings.Sample;
            TestBorder.Thickness = Terminal.Gui.Drawing.Thickness.1;
        }
    }
}
