// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class BorderViewTest : Terminal.Gui.ViewBase.BorderView
    {
        private Terminal.Gui.ViewBase.BorderView TestBorderView = null!;

        private void InitializeComponent()
        {
            TestBorderView = this;
            TestBorderView.Diagnostics = Terminal.Gui.ViewBase.ViewDiagnosticFlags.DrawIndicator;
        }
    }
}
