// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ButtonTest : Terminal.Gui.Views.Button
    {
        private Terminal.Gui.Views.Button TestButton = null!;

        private void InitializeComponent()
        {
            TestButton = this;
            TestButton.X = 5;
            TestButton.Y = 2;
            TestButton.Width = 30;
            TestButton.Height = 5;
            TestButton.IsDefault = true;
            TestButton.NoDecorations = true;
            TestButton.NoPadding = true;
            TestButton.Accepting += OnAccepting;

            SetupBindings();
        }

        private void SetupBindings()
        {
            TestButton.Accepted += (s, e) => {
                if (AcceptedCommand?.CanExecute(null) == true)
                    AcceptedCommand.Execute(e);
            };

            PropertyChanged += OnViewModelPropertyChanged;
            // Subscribe to CanExecuteChanged for TestButton
            if (AcceptedCommand != null)
            {
                AcceptedCommand.CanExecuteChanged += (s, e) => {
                    TestButton.Enabled = AcceptedCommand.CanExecute(null);
                };
                // Set initial Enabled state
                TestButton.Enabled = AcceptedCommand.CanExecute(null);
            }
        }

        private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
        {
            switch (e.PropertyName)
            {
                default:
                    break;
            }
        }
    }
}
