// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ButtonTest : Terminal.Gui.Views.Button
    {
        private Terminal.Gui.Views.Button ButtonTest1 = null!;

        private void InitializeComponent()
        {
            ButtonTest1 = this;
            ButtonTest1.Text = "Click Me!";
            ButtonTest1.X = Pos.Center();
            ButtonTest1.Y = Pos.Center();
        }
    }
}
