// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class CharMapTest : Terminal.Gui.Views.CharMap
    {
        private Terminal.Gui.Views.CharMap TestCharMap = null!;

        private void InitializeComponent()
        {
            TestCharMap = this;
            TestCharMap.X = 5;
            TestCharMap.Y = 2;
            TestCharMap.Width = 30;
            TestCharMap.Height = 5;
            TestCharMap.SelectedCodePoint = 0;
            TestCharMap.ShowGlyphWidths = true;
            TestCharMap.StartCodePoint = 0;
        }
    }
}
