// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class CharMapTest : Terminal.Gui.Views.CharMap
    {
        private Terminal.Gui.Views.CharMap CharMap1 = null!;

        private void InitializeComponent()
        {
            CharMap1 = this;
            CharMap1.X = Pos.Center();
            CharMap1.Y = Pos.Center();
        }
    }
}
