// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class CheckBoxTest : Terminal.Gui.Views.CheckBox
    {
        private Terminal.Gui.Views.CheckBox TestCheckBox = null!;

        private void InitializeComponent()
        {
            TestCheckBox = this;
            TestCheckBox.X = 5;
            TestCheckBox.Y = 2;
            TestCheckBox.Width = 30;
            TestCheckBox.Height = 5;
            TestCheckBox.Value = Terminal.Gui.Views.CheckState.Checked;
            TestCheckBox.AllowCheckStateNone = true;
            TestCheckBox.RadioStyle = false;
        }
    }
}
