// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class CheckBoxTest : Terminal.Gui.Views.CheckBox
    {
        private Terminal.Gui.Views.CheckBox CheckBox1 = null!;

        private void InitializeComponent()
        {
            CheckBox1 = this;
            CheckBox1.X = Pos.Center();
            CheckBox1.Y = Pos.Center();
        }
    }
}
