// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ColorPicker16Test : Terminal.Gui.Views.ColorPicker16
    {
        private Terminal.Gui.Views.ColorPicker16 TestColorPicker16 = null!;

        private void InitializeComponent()
        {
            TestColorPicker16 = this;
            TestColorPicker16.X = 5;
            TestColorPicker16.Y = 2;
            TestColorPicker16.Width = 30;
            TestColorPicker16.Height = 5;
            TestColorPicker16.BoxHeight = 4;
            TestColorPicker16.BoxWidth = 4;
        }
    }
}
