// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ColorPickerTest : Terminal.Gui.Views.ColorPicker
    {
        private Terminal.Gui.Views.ColorPicker ColorPicker1 = null!;

        private void InitializeComponent()
        {
            ColorPicker1 = this;
            ColorPicker1.X = Pos.Center();
            ColorPicker1.Y = Pos.Center();
        }
    }
}
