// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ColorPicker16Test : Terminal.Gui.Views.ColorPicker16
    {
        private Terminal.Gui.Views.ColorPicker16 ColorPicker161 = null!;

        private void InitializeComponent()
        {
            ColorPicker161 = this;
            ColorPicker161.X = Pos.Center();
            ColorPicker161.Y = Pos.Center();
        }
    }
}
