// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ColorPickerTest : Terminal.Gui.Views.ColorPicker
    {
        private Terminal.Gui.Views.ColorPicker TestColorPicker = null!;

        private void InitializeComponent()
        {
            TestColorPicker = this;
            TestColorPicker.X = 5;
            TestColorPicker.Y = 2;
            TestColorPicker.Width = 30;
            TestColorPicker.Height = 5;
            TestColorPicker.SelectedColor = Terminal.Gui.Drawing.Color.Yellow;
            TestColorPicker.Value = Terminal.Gui.Drawing.Color.Blue;
        }
    }
}
