// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class ComboBoxTestView : Terminal.Gui.Views.ComboBox
    {
        private Terminal.Gui.Views.ComboBox TestComboBox = null!;

        private void InitializeComponent()
        {
            TestComboBox = this;
            TestComboBox.X = 5;
            TestComboBox.Y = 2;
            TestComboBox.Width = 30;
            TestComboBox.Height = 5;
            TestComboBox.HideDropdownListOnClick = Sample;
            TestComboBox.SearchText = "Sample";
            TestComboBox.SelectedItem = 0;
            TestComboBox.Source = Terminal.Gui.Views.IListDataSource.;
        }
    }
}
