// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class DateFieldTestView : Terminal.Gui.Views.DateField
    {
        private Terminal.Gui.Views.DateField TestDateField = null!;

        private void InitializeComponent()
        {
            TestDateField = this;
            TestDateField.X = 5;
            TestDateField.Y = 2;
            TestDateField.Width = 30;
            TestDateField.Height = 5;
            TestDateField.Autocomplete = Terminal.Gui.Views.IAutocomplete.Sample;
            TestDateField.Culture = "Sample";
            TestDateField.InsertionPoint = "Sample";
            TestDateField.Secret = Sample;
            TestDateField.SelectedStart = 0;
        }
    }
}
