// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class DateEditorTest : Terminal.Gui.Views.DateEditor
    {
        private Terminal.Gui.Views.DateEditor TestDateEditor = null!;

        private void InitializeComponent()
        {
            TestDateEditor = this;
            TestDateEditor.X = 5;
            TestDateEditor.Y = 2;
            TestDateEditor.Width = 30;
            TestDateEditor.Height = 5;
        }
    }
}
