// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class DatePickerTest : Terminal.Gui.Views.DatePicker
    {
        private Terminal.Gui.Views.DatePicker TestDatePicker = null!;

        private void InitializeComponent()
        {
            TestDatePicker = this;
            TestDatePicker.X = 5;
            TestDatePicker.Y = 2;
            TestDatePicker.Width = 30;
            TestDatePicker.Height = 5;
        }
    }
}
