// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class DialogTest : Terminal.Gui.Views.Dialog
    {
        private Terminal.Gui.Views.Dialog TestDialog = null!;

        private void InitializeComponent()
        {
            TestDialog = this;
        }
    }
}
