// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class FileDialogTestView : Terminal.Gui.Views.FileDialog
    {
        private Terminal.Gui.Views.FileDialog TestFileDialog = null!;

        private void InitializeComponent()
        {
            TestFileDialog = this;
            TestFileDialog.X = 5;
            TestFileDialog.Y = 2;
            TestFileDialog.Width = 30;
            TestFileDialog.Height = 5;
            TestFileDialog.OpenMode = Terminal.Gui.Views.OpenMode.File;
        }
    }
}
