// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class FlagSelectorTest : Terminal.Gui.Views.FlagSelector
    {
        private Terminal.Gui.Views.FlagSelector TestFlagSelector = null!;

        private void InitializeComponent()
        {
            TestFlagSelector = this;
            TestFlagSelector.X = 5;
            TestFlagSelector.Y = 2;
            TestFlagSelector.Width = 30;
            TestFlagSelector.Height = 5;
            TestFlagSelector.DoubleClickAccepts = Sample;
            TestFlagSelector.HorizontalSpace = "Sample";
            TestFlagSelector.Labels = "Sample";
            TestFlagSelector.Styles = Terminal.Gui.Views.SelectorStyles.Sample;
            TestFlagSelector.TabBehavior = "Sample";
        }
    }
}
