// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class FlagSelectorTest : Terminal.Gui.Views.FlagSelector
    {
        private Terminal.Gui.Views.FlagSelector FlagSelector1 = null!;

        private void InitializeComponent()
        {
            FlagSelector1 = this;
            FlagSelector1.X = Pos.Center();
            FlagSelector1.Y = Pos.Center();
        }
    }
}
