// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class FrameViewTest : Terminal.Gui.Views.FrameView
    {
        private Terminal.Gui.Views.FrameView FrameView1 = null!;

        private void InitializeComponent()
        {
            FrameView1 = this;
            FrameView1.X = Pos.Center();
            FrameView1.Y = Pos.Center();
        }
    }
}
