// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class GraphViewTest : Terminal.Gui.Views.GraphView
    {
        private Terminal.Gui.Views.GraphView GraphView1 = null!;

        private void InitializeComponent()
        {
            GraphView1 = this;
            GraphView1.X = Pos.Center();
            GraphView1.Y = Pos.Center();
        }
    }
}
