// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class GraphViewTest : Terminal.Gui.Views.GraphView
    {
        private Terminal.Gui.Views.GraphView TestGraphView = null!;

        private void InitializeComponent()
        {
            TestGraphView = this;
            TestGraphView.X = 5;
            TestGraphView.Y = 2;
            TestGraphView.Width = 30;
            TestGraphView.Height = 5;
            TestGraphView.AxisX = Terminal.Gui.Views.HorizontalAxis.Sample;
            TestGraphView.AxisY = Terminal.Gui.Views.VerticalAxis.Sample;
        }
    }
}
