// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class HexViewTest : Terminal.Gui.Views.HexView
    {
        private Terminal.Gui.Views.HexView HexView1 = null!;

        private void InitializeComponent()
        {
            HexView1 = this;
            HexView1.X = Pos.Center();
            HexView1.Y = Pos.Center();
        }
    }
}
