// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class HexViewTest : Terminal.Gui.Views.HexView
    {
        private Terminal.Gui.Views.HexView TestHexView = null!;

        private void InitializeComponent()
        {
            TestHexView = this;
            TestHexView.X = 5;
            TestHexView.Y = 2;
            TestHexView.Width = 30;
            TestHexView.Height = 5;
            TestHexView.Address = "Sample";
            TestHexView.AddressWidth = "Sample";
            TestHexView.BytesPerLine = "Sample";
            TestHexView.Source = "";
        }
    }
}
