// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class LabelTest : Terminal.Gui.Views.Label
    {
        private Terminal.Gui.Views.Label Label1 = null!;

        private void InitializeComponent()
        {
            Label1 = this;
            Label1.X = Pos.Center();
            Label1.Y = Pos.Center();
        }
    }
}
