// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class LegendAnnotationTest : Terminal.Gui.Views.LegendAnnotation
    {
        private Terminal.Gui.Views.LegendAnnotation TestControl = null!;

        private void InitializeComponent()
        {
            TestControl = this;
            TestControl.X = 5;
            TestControl.Y = 2;
            TestControl.Width = 30;
            TestControl.Height = 5;
        }
    }
}
