// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class LinearRangeTest : Terminal.Gui.Views.LinearRange
    {
        private Terminal.Gui.Views.LinearRange TestLinearRange = null!;

        private void InitializeComponent()
        {
            TestLinearRange = this;
            TestLinearRange.X = 5;
            TestLinearRange.Y = 2;
            TestLinearRange.Width = 30;
            TestLinearRange.Height = 5;
            TestLinearRange.LegendsOrientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
        }
    }
}
