// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class LinearRangeTest : Terminal.Gui.Views.LinearRange
    {
        private Terminal.Gui.Views.LinearRange LinearRange1 = null!;

        private void InitializeComponent()
        {
            LinearRange1 = this;
            LinearRange1.X = Pos.Center();
            LinearRange1.Y = Pos.Center();
        }
    }
}
