// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class LineTest : Terminal.Gui.Views.Line
    {
        private Terminal.Gui.Views.Line Line1 = null!;

        private void InitializeComponent()
        {
            Line1 = this;
            Line1.X = Pos.Center();
            Line1.Y = Pos.Center();
        }
    }
}
