// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class LineTest : Terminal.Gui.Views.Line
    {
        private Terminal.Gui.Views.Line TestLine = null!;

        private void InitializeComponent()
        {
            TestLine = this;
            TestLine.X = 5;
            TestLine.Y = 2;
            TestLine.Width = 30;
            TestLine.Height = 5;
            TestLine.Length = Dim.Auto();
            TestLine.Style = Terminal.Gui.Drawing.LineStyle.Sample;
        }
    }
}
