// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class LinkTest : Terminal.Gui.Views.Link
    {
        private Terminal.Gui.Views.Link Link1 = null!;

        private void InitializeComponent()
        {
            Link1 = this;
            Link1.X = Pos.Center();
            Link1.Y = Pos.Center();
            Link1.Url = "https://github.com/tool2team/t2t-terminal-gui-xamllike";
        }
    }
}
