// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ListViewTest : Terminal.Gui.Views.ListView
    {
        private Terminal.Gui.Views.ListView TestListView = null!;

        private void InitializeComponent()
        {
            TestListView = this;
            TestListView.X = 5;
            TestListView.Y = 2;
            TestListView.Width = 30;
            TestListView.Height = 5;
            TestListView.MarkMultiple = true;
            TestListView.SelectedItem = 0;
            TestListView.ShowMarks = false;
        }
    }
}
