// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ListViewTest : Terminal.Gui.Views.ListView
    {
        private Terminal.Gui.Views.ListView ListView1 = null!;

        private void InitializeComponent()
        {
            ListView1 = this;
            ListView1.X = Pos.Center();
            ListView1.Y = Pos.Center();
        }
    }
}
