// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class MarginTest : Terminal.Gui.ViewBase.Margin
    {
        private Terminal.Gui.ViewBase.Margin TestMargin = null!;

        private void InitializeComponent()
        {
            TestMargin = this;
            TestMargin.Diagnostics = Terminal.Gui.ViewBase.ViewDiagnosticFlags.DrawIndicator;
            TestMargin.ShadowSize = new System.Drawing.Size(1, 1);
            TestMargin.Thickness = Terminal.Gui.Drawing.Thickness.Empty;
        }
    }
}
