// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class MarginTestView : Terminal.Gui.ViewBase.Margin
    {
        private Terminal.Gui.ViewBase.Margin TestMargin = null!;

        private void InitializeComponent()
        {
            TestMargin = this;
            TestMargin.Diagnostics = Terminal.Gui.ViewBase.ViewDiagnosticFlags.Sample;
            TestMargin.Parent = Terminal.Gui.ViewBase.View.Sample;
            TestMargin.ShadowSize = "Sample";
            TestMargin.Thickness = Terminal.Gui.Drawing.Thickness.1;
        }
    }
}
