// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class MarginViewTest : Terminal.Gui.ViewBase.MarginView
    {
        private Terminal.Gui.ViewBase.MarginView TestMarginView = null!;

        private void InitializeComponent()
        {
            TestMarginView = this;
            TestMarginView.Diagnostics = Terminal.Gui.ViewBase.ViewDiagnosticFlags.DrawIndicator;
            TestMarginView.ShadowSize = new System.Drawing.Size(1, 1);
        }
    }
}
