// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class MenuTest : Terminal.Gui.Views.Menu
    {
        private Terminal.Gui.Views.Menu TestMenu = null!;

        private void InitializeComponent()
        {
            TestMenu = this;
            TestMenu.X = 5;
            TestMenu.Y = 2;
            TestMenu.Width = 30;
            TestMenu.Height = 5;
            TestMenu.SuperMenuItem = Terminal.Gui.Views.MenuItem.Sample;
            TestMenu.Value = Terminal.Gui.Views.MenuItem.0;
        }
    }
}
