// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class MenuTest : Terminal.Gui.Views.Menu
    {
        private Terminal.Gui.Views.Menu Menu1 = null!;

        private void InitializeComponent()
        {
            Menu1 = this;
            Menu1.X = Pos.Center();
            Menu1.Y = Pos.Center();
        }
    }
}
