// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class MenuBarItemTest : Terminal.Gui.Views.MenuBarItem
    {
        private Terminal.Gui.Views.MenuBarItem TestMenuBarItem = null!;

        private void InitializeComponent()
        {
            TestMenuBarItem = this;
            TestMenuBarItem.X = 5;
            TestMenuBarItem.Y = 2;
            TestMenuBarItem.Width = 30;
            TestMenuBarItem.Height = 5;
            TestMenuBarItem.Action = "Sample";
            TestMenuBarItem.BindKeyToApplication = Sample;
            TestMenuBarItem.Command = Terminal.Gui.Input.Command.Sample;
            TestMenuBarItem.CommandView = Terminal.Gui.ViewBase.View.Sample;
            TestMenuBarItem.HelpText = "Sample";
        }
    }
}
