// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class MenuItemTestView : Terminal.Gui.Views.MenuItem
    {
        private Terminal.Gui.Views.MenuItem TestMenuItem = null!;

        private void InitializeComponent()
        {
            TestMenuItem = this;
            TestMenuItem.X = 5;
            TestMenuItem.Y = 2;
            TestMenuItem.Width = 30;
            TestMenuItem.Height = 5;
            TestMenuItem.BindKeyToApplication = true;
            TestMenuItem.HelpText = "Sample";
        }
    }
}
