// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class MenuBarTest : Terminal.Gui.Views.MenuBar
    {
        private Terminal.Gui.Views.MenuBar TestMenuBar = null!;

        private void InitializeComponent()
        {
            TestMenuBar = this;
            TestMenuBar.Menus = Terminal.Gui.Views.MenuBarItem[].Sample;
            TestMenuBar.SuperMenuItem = Terminal.Gui.Views.MenuItem.Sample;
            TestMenuBar.Value = Terminal.Gui.Views.MenuItem.0;
        }
    }
}
