// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class MenuBarItemTest : Terminal.Gui.Views.MenuBarItem
    {
        private Terminal.Gui.Views.MenuBarItem MenuBarItem1 = null!;

        private void InitializeComponent()
        {
            MenuBarItem1 = this;
            MenuBarItem1.X = Pos.Center();
            MenuBarItem1.Y = Pos.Center();
        }
    }
}
