// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class NumericUpDownTest : Terminal.Gui.Views.NumericUpDown
    {
        private Terminal.Gui.Views.NumericUpDown TestNumericUpDown = null!;

        private void InitializeComponent()
        {
            TestNumericUpDown = this;
            TestNumericUpDown.X = 5;
            TestNumericUpDown.Y = 2;
            TestNumericUpDown.Width = 30;
            TestNumericUpDown.Height = 5;
            TestNumericUpDown.Format = "Sample";
            TestNumericUpDown.Increment = 2;
            TestNumericUpDown.Value = 0;
        }
    }
}
