// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class NumericUpDownTest : Terminal.Gui.Views.NumericUpDown
    {
        private Terminal.Gui.Views.NumericUpDown NumericUpDown1 = null!;

        private void InitializeComponent()
        {
            NumericUpDown1 = this;
            NumericUpDown1.X = Pos.Center();
            NumericUpDown1.Y = Pos.Center();
        }
    }
}
