// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class OpenDialogTest : Terminal.Gui.Views.OpenDialog
    {
        private Terminal.Gui.Views.OpenDialog OpenDialog1 = null!;

        private void InitializeComponent()
        {
            OpenDialog1 = this;
            OpenDialog1.X = Pos.Center();
            OpenDialog1.Y = Pos.Center();
        }
    }
}
