// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class OpenDialogTest : Terminal.Gui.Views.OpenDialog
    {
        private Terminal.Gui.Views.OpenDialog TestOpenDialog = null!;

        private void InitializeComponent()
        {
            TestOpenDialog = this;
            TestOpenDialog.X = 5;
            TestOpenDialog.Y = 2;
            TestOpenDialog.Width = 30;
            TestOpenDialog.Height = 5;
            TestOpenDialog.OpenMode = Terminal.Gui.Views.OpenMode.File;
        }
    }
}
