// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class OptionSelectorTest : Terminal.Gui.Views.OptionSelector
    {
        private Terminal.Gui.Views.OptionSelector TestOptionSelector = null!;

        private void InitializeComponent()
        {
            TestOptionSelector = this;
            TestOptionSelector.X = 5;
            TestOptionSelector.Y = 2;
            TestOptionSelector.Width = 30;
            TestOptionSelector.Height = 5;
            TestOptionSelector.DoubleClickAccepts = true;
            TestOptionSelector.FocusedItem = 1;
            TestOptionSelector.HorizontalSpace = 2;
            TestOptionSelector.Styles = Terminal.Gui.Views.SelectorStyles.All;
        }
    }
}
