// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class OptionSelectorTest : Terminal.Gui.Views.OptionSelector
    {
        private Terminal.Gui.Views.OptionSelector OptionSelector1 = null!;

        private void InitializeComponent()
        {
            OptionSelector1 = this;
            OptionSelector1.X = Pos.Center();
            OptionSelector1.Y = Pos.Center();
        }
    }
}
