// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class PaddingViewTest : Terminal.Gui.ViewBase.PaddingView
    {
        private Terminal.Gui.ViewBase.PaddingView TestPaddingView = null!;

        private void InitializeComponent()
        {
            TestPaddingView = this;
            TestPaddingView.Diagnostics = Terminal.Gui.ViewBase.ViewDiagnosticFlags.DrawIndicator;
        }
    }
}
