// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class PaddingTestView : Terminal.Gui.ViewBase.Padding
    {
        private Terminal.Gui.ViewBase.Padding TestPadding = null!;

        private void InitializeComponent()
        {
            TestPadding = this;
            TestPadding.Diagnostics = Terminal.Gui.ViewBase.ViewDiagnosticFlags.Sample;
            TestPadding.Parent = Terminal.Gui.ViewBase.View.Sample;
            TestPadding.Thickness = Terminal.Gui.Drawing.Thickness.1;
        }
    }
}
