// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class PopoverMenuTestView : Terminal.Gui.Views.PopoverMenu
    {
        private Terminal.Gui.Views.PopoverMenu TestPopoverMenu = null!;

        private void InitializeComponent()
        {
            TestPopoverMenu = this;
            TestPopoverMenu.X = 5;
            TestPopoverMenu.Y = 2;
            TestPopoverMenu.Width = 30;
            TestPopoverMenu.Height = 5;
            TestPopoverMenu.MouseFlags = Terminal.Gui.Input.MouseFlags.Sample;
            TestPopoverMenu.Owner = Terminal.Gui.App.IRunnable.Sample;
            TestPopoverMenu.Root = Terminal.Gui.Views.Menu.Sample;
        }
    }
}
