// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ProgressBarTest : Terminal.Gui.Views.ProgressBar
    {
        private Terminal.Gui.Views.ProgressBar ProgressBar1 = null!;

        private void InitializeComponent()
        {
            ProgressBar1 = this;
            ProgressBar1.X = Pos.Center();
            ProgressBar1.Y = Pos.Center();
        }
    }
}
