// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ProgressBarTest : Terminal.Gui.Views.ProgressBar
    {
        private Terminal.Gui.Views.ProgressBar TestProgressBar = null!;

        private void InitializeComponent()
        {
            TestProgressBar = this;
            TestProgressBar.X = 5;
            TestProgressBar.Y = 2;
            TestProgressBar.Width = 30;
            TestProgressBar.Height = 5;
            TestProgressBar.BidirectionalMarquee = false;
            TestProgressBar.ProgressBarFormat = Terminal.Gui.Views.ProgressBarFormat.Simple;
            TestProgressBar.ProgressBarStyle = Terminal.Gui.Views.ProgressBarStyle.Continuous;
            TestProgressBar.SegmentCharacter = new System.Text.Rune('¼');
        }
    }
}
