// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class RunnableTest : Terminal.Gui.Views.Runnable
    {
        private Terminal.Gui.Views.Runnable TestRunnable = null!;

        private void InitializeComponent()
        {
            TestRunnable = this;
            TestRunnable.X = 5;
            TestRunnable.Y = 2;
            TestRunnable.Width = 30;
            TestRunnable.Height = 5;
        }
    }
}
