// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class SaveDialogTest : Terminal.Gui.Views.SaveDialog
    {
        private Terminal.Gui.Views.SaveDialog SaveDialog1 = null!;

        private void InitializeComponent()
        {
            SaveDialog1 = this;
            SaveDialog1.X = Pos.Center();
            SaveDialog1.Y = Pos.Center();
        }
    }
}
