// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class SaveDialogTest : Terminal.Gui.Views.SaveDialog
    {
        private Terminal.Gui.Views.SaveDialog TestSaveDialog = null!;

        private void InitializeComponent()
        {
            TestSaveDialog = this;
            TestSaveDialog.X = 5;
            TestSaveDialog.Y = 2;
            TestSaveDialog.Width = 30;
            TestSaveDialog.Height = 5;
            TestSaveDialog.AllowedTypes = "Sample";
            TestSaveDialog.AllowsMultipleSelection = Sample;
            TestSaveDialog.FileOperationsHandler = Terminal.Gui.FileServices.IFileOperations.Sample;
            TestSaveDialog.MustExist = Sample;
            TestSaveDialog.OpenMode = Terminal.Gui.Views.OpenMode.Sample;
        }
    }
}
