// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class ScrollSliderTestView : Terminal.Gui.Views.ScrollSlider
    {

        private void InitializeComponent()
        {
            this.Width = 40;
            this.Height = 10;
        }
    }
}
