// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ScrollBarTest : Terminal.Gui.Views.ScrollBar
    {
        private Terminal.Gui.Views.ScrollBar TestScrollBar = null!;

        private void InitializeComponent()
        {
            TestScrollBar = this;
            TestScrollBar.X = 5;
            TestScrollBar.Y = 2;
            TestScrollBar.Width = 30;
            TestScrollBar.Height = 5;
            TestScrollBar.Increment = "Sample";
            TestScrollBar.ScrollableContentSize = "Sample";
            TestScrollBar.Value = "0";
            TestScrollBar.VisibilityMode = Terminal.Gui.Views.ScrollBarVisibilityMode.Sample;
            TestScrollBar.VisibleContentSize = "Sample";
        }
    }
}
