// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ScrollBarTest : Terminal.Gui.Views.ScrollBar
    {
        private Terminal.Gui.Views.ScrollBar ScrollBar1 = null!;

        private void InitializeComponent()
        {
            ScrollBar1 = this;
            ScrollBar1.X = Pos.Center();
            ScrollBar1.Y = Pos.Center();
        }
    }
}
