// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ShortcutTest : Terminal.Gui.Views.Shortcut
    {
        private Terminal.Gui.Views.Shortcut Shortcut1 = null!;

        private void InitializeComponent()
        {
            Shortcut1 = this;
            Shortcut1.X = Pos.Center();
            Shortcut1.Y = Pos.Center();
        }
    }
}
