// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ShortcutTest : Terminal.Gui.Views.Shortcut
    {
        private Terminal.Gui.Views.Shortcut TestShortcut = null!;

        private void InitializeComponent()
        {
            TestShortcut = this;
            TestShortcut.X = 5;
            TestShortcut.Y = 2;
            TestShortcut.Width = 30;
            TestShortcut.Height = 5;
            TestShortcut.HelpText = "Sample";
        }
    }
}
