// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class SpinnerViewTest : Terminal.Gui.Views.SpinnerView
    {
        private Terminal.Gui.Views.SpinnerView TestSpinnerView = null!;

        private void InitializeComponent()
        {
            TestSpinnerView = this;
            TestSpinnerView.X = 5;
            TestSpinnerView.Y = 2;
            TestSpinnerView.Width = 30;
            TestSpinnerView.Height = 5;
            TestSpinnerView.AutoSpin = true;
            TestSpinnerView.Sequence = ["/", "-", "\\", "|"];
            TestSpinnerView.SpinBounce = true;
            TestSpinnerView.SpinDelay = 5;
            TestSpinnerView.SpinReverse = false;
        }
    }
}
