// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class SpinnerViewTest : Terminal.Gui.Views.SpinnerView
    {
        private Terminal.Gui.Views.SpinnerView SpinnerView1 = null!;

        private void InitializeComponent()
        {
            SpinnerView1 = this;
            SpinnerView1.X = Pos.Center();
            SpinnerView1.Y = Pos.Center();
        }
    }
}
