// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class StatusBarTest : Terminal.Gui.Views.StatusBar
    {
        private Terminal.Gui.Views.StatusBar StatusBar1 = null!;

        private void InitializeComponent()
        {
            StatusBar1 = this;
            StatusBar1.X = Pos.Center();
            StatusBar1.Y = Pos.Center();
        }
    }
}
