// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TableViewTest : Terminal.Gui.Views.TableView
    {
        private Terminal.Gui.Views.TableView TableView1 = null!;

        private void InitializeComponent()
        {
            TableView1 = this;
            TableView1.X = Pos.Center();
            TableView1.Y = Pos.Center();
        }
    }
}
