// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TableViewTest : Terminal.Gui.Views.TableView
    {
        private Terminal.Gui.Views.TableView TestTableView = null!;

        private void InitializeComponent()
        {
            TestTableView = this;
            TestTableView.X = 5;
            TestTableView.Y = 2;
            TestTableView.Width = 30;
            TestTableView.Height = 5;
            TestTableView.CellActivationKey = Terminal.Gui.Drivers.KeyCode.Z;
        }
    }
}
