// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TabsTest : Terminal.Gui.Views.Tabs
    {
        private Terminal.Gui.Views.Tabs TestTabs = null!;

        private void InitializeComponent()
        {
            TestTabs = this;
            TestTabs.X = 5;
            TestTabs.Y = 2;
            TestTabs.Width = 30;
            TestTabs.Height = 5;
            TestTabs.Text = "Display";
        }
    }
}
