// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TabTest : Terminal.Gui.Views.Tab
    {
        private Terminal.Gui.Views.Tab Tab1 = null!;

        private void InitializeComponent()
        {
            Tab1 = this;
            Tab1.X = Pos.Center();
            Tab1.Y = Pos.Center();
        }
    }
}
