// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TabTest : Terminal.Gui.Views.Tab
    {
        private Terminal.Gui.Views.Tab TestTab = null!;

        private void InitializeComponent()
        {
            TestTab = this;
            TestTab.X = 5;
            TestTab.Y = 2;
            TestTab.Width = 30;
            TestTab.Height = 5;
            TestTab.DisplayText = "Display";
        }
    }
}
