// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TabViewTest : Terminal.Gui.Views.TabView
    {
        private Terminal.Gui.Views.TabView TabView1 = null!;

        private void InitializeComponent()
        {
            TabView1 = this;
            TabView1.X = Pos.Center();
            TabView1.Y = Pos.Center();
        }
    }
}
