// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TabViewTest : Terminal.Gui.Views.TabView
    {
        private Terminal.Gui.Views.TabView TestTabView = null!;

        private void InitializeComponent()
        {
            TestTabView = this;
            TestTabView.X = 5;
            TestTabView.Y = 2;
            TestTabView.Width = 30;
            TestTabView.Height = 5;
            TestTabView.TabScrollOffset = 2;
        }
    }
}
