// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TextFieldTest : Terminal.Gui.Views.TextField
    {
        private Terminal.Gui.Views.TextField TestTextField = null!;

        private void InitializeComponent()
        {
            TestTextField = this;
            TestTextField.X = 5;
            TestTextField.Y = 2;
            TestTextField.Width = 30;
            TestTextField.Height = 5;
            TestTextField.Autocomplete = Terminal.Gui.Views.IAutocomplete.Sample;
            TestTextField.InsertionPoint = "Sample";
            TestTextField.Secret = Sample;
            TestTextField.SelectedStart = 0;
            TestTextField.SelectWordOnlyOnDoubleClick = Sample;
        }
    }
}
