// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TextViewTest : Terminal.Gui.Views.TextView
    {
        private Terminal.Gui.Views.TextView TextView1 = null!;

        private void InitializeComponent()
        {
            TextView1 = this;
            TextView1.X = Pos.Center();
            TextView1.Y = Pos.Center();
        }
    }
}
