// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class TextValidateFieldTestView : Terminal.Gui.Views.TextValidateField
    {
        private Terminal.Gui.Views.TextValidateField TestTextValidateField = null!;

        private void InitializeComponent()
        {
            TestTextValidateField = this;
            TestTextValidateField.X = 5;
            TestTextValidateField.Y = 2;
            TestTextValidateField.Width = 30;
            TestTextValidateField.Height = 5;
        }
    }
}
