// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TextFieldTest : Terminal.Gui.Views.TextField
    {
        private Terminal.Gui.Views.TextField TextField1 = null!;

        private void InitializeComponent()
        {
            TextField1 = this;
            TextField1.X = Pos.Center();
            TextField1.Y = Pos.Center();
        }
    }
}
