// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TextViewTest : Terminal.Gui.Views.TextView
    {
        private Terminal.Gui.Views.TextView TestTextView = null!;

        private void InitializeComponent()
        {
            TestTextView = this;
            TestTextView.X = 5;
            TestTextView.Y = 2;
            TestTextView.Width = 30;
            TestTextView.Height = 5;
            TestTextView.Multiline = false;
        }
    }
}
