// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class TimeEditorTest : Terminal.Gui.Views.TimeEditor
    {
        private Terminal.Gui.Views.TimeEditor TestTimeEditor = null!;

        private void InitializeComponent()
        {
            TestTimeEditor = this;
            TestTimeEditor.X = 5;
            TestTimeEditor.Y = 2;
            TestTimeEditor.Width = 30;
            TestTimeEditor.Height = 5;
        }
    }
}
