// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Views
{
    partial class TimeFieldTestView : Terminal.Gui.Views.TimeField
    {
        private Terminal.Gui.Views.TimeField TestTimeField = null!;

        private void InitializeComponent()
        {
            TestTimeField = this;
            TestTimeField.X = 5;
            TestTimeField.Y = 2;
            TestTimeField.Width = 30;
            TestTimeField.Height = 5;
            TestTimeField.Autocomplete = Terminal.Gui.Views.IAutocomplete.Sample;
            TestTimeField.SelectedStart = 0;
        }
    }
}
