// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TreeViewTest : Terminal.Gui.Views.TreeView
    {
        private Terminal.Gui.Views.TreeView TestTreeView = null!;

        private void InitializeComponent()
        {
            TestTreeView = this;
            TestTreeView.X = 5;
            TestTreeView.Y = 2;
            TestTreeView.Width = 30;
            TestTreeView.Height = 5;
        }
    }
}
