// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class TreeViewTest : Terminal.Gui.Views.TreeView
    {
        private Terminal.Gui.Views.TreeView TreeView1 = null!;

        private void InitializeComponent()
        {
            TreeView1 = this;
            TreeView1.X = Pos.Center();
            TreeView1.Y = Pos.Center();
        }
    }
}
