// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class ViewTest : Terminal.Gui.ViewBase.View
    {
        private Terminal.Gui.ViewBase.View View1 = null!;

        private void InitializeComponent()
        {
            View1 = this;
            View1.X = Pos.Center();
            View1.Y = Pos.Center();
        }
    }
}
