// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class WindowTest : Terminal.Gui.Views.Window
    {
        private Terminal.Gui.Views.Window TestWindow = null!;

        private void InitializeComponent()
        {
            TestWindow = this;
        }
    }
}
