// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class WindowTest : Terminal.Gui.Views.Window
    {
        private Terminal.Gui.Views.Window Window1 = null!;

        private void InitializeComponent()
        {
            Window1 = this;
            Window1.X = Pos.Center();
            Window1.Y = Pos.Center();
        }
    }
}
