// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class WizardStepTest : Terminal.Gui.Views.WizardStep
    {
        private Terminal.Gui.Views.WizardStep TestWizardStep = null!;

        private void InitializeComponent()
        {
            TestWizardStep = this;
            TestWizardStep.X = 5;
            TestWizardStep.Y = 2;
            TestWizardStep.Width = 30;
            TestWizardStep.Height = 5;
            TestWizardStep.BackButtonText = "Sample";
            TestWizardStep.HelpText = "Sample";
            TestWizardStep.NextButtonText = "Sample";
        }
    }
}
