// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class WizardTest : Terminal.Gui.Views.Wizard
    {
        private Terminal.Gui.Views.Wizard TestWizard = null!;

        private void InitializeComponent()
        {
            TestWizard = this;
            TestWizard.X = 5;
            TestWizard.Y = 2;
            TestWizard.Width = 30;
            TestWizard.Height = 5;
        }
    }
}
