// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class WizardStepTest : Terminal.Gui.Views.WizardStep
    {
        private Terminal.Gui.Views.WizardStep WizardStep1 = null!;

        private void InitializeComponent()
        {
            WizardStep1 = this;
            WizardStep1.X = Pos.Center();
            WizardStep1.Y = Pos.Center();
        }
    }
}
