// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using Terminal.Gui;
using Terminal.Gui.Views;
using Terminal.Gui.ViewBase;

namespace Terminal.Gui.XamlLike.Tests.Integration.Xaml
{
    partial class WizardTest : Terminal.Gui.Views.Wizard
    {
        private Terminal.Gui.Views.Wizard Wizard1 = null!;

        private void InitializeComponent()
        {
            Wizard1 = this;
            Wizard1.X = Pos.Center();
            Wizard1.Y = Pos.Center();
        }
    }
}
