// <auto-generated />
// Generated by Terminal.Gui.MetadataExtractor
// Generated at: 2026-03-03 23:20:25

#nullable enable

using System.Collections.Generic;

namespace Terminal.Gui.XamlLike;

/// <summary>
/// Information about a Terminal.Gui control type
/// </summary>
public class ControlMapping
{
    public string FullTypeName { get; }
    public string Namespace { get; }
    public bool IsContainer { get; }
    public string? Description { get; }

    public ControlMapping(string fullTypeName, string namespaceName, bool isContainer = false, string? description = null)
    {
        FullTypeName = fullTypeName;
        Namespace = namespaceName;
        IsContainer = isContainer;
        Description = description;
    }
}

/// <summary>
/// Information about an event mapping
/// </summary>
public class EventMapping
{
    public string EventName { get; }
    public string DelegateType { get; }

    public EventMapping(string eventName, string delegateType)
    {
        EventName = eventName;
        DelegateType = delegateType;
    }
}

/// <summary>
/// Information about a TwoWay bindable property
/// </summary>
public class TwoWayBinding
{
    public string PropertyName { get; }
    public string ChangeEventName { get; }

    public TwoWayBinding(string propertyName, string changeEventName)
    {
        PropertyName = propertyName;
        ChangeEventName = changeEventName;
    }
}

/// <summary>
/// Information about a property mapping
/// </summary>
public class PropertyMapping
{
    public string PropertyName { get; }
    public string TargetType { get; }
    public bool IsNullable { get; }

    public PropertyMapping(string propertyName, string targetType, bool isNullable = false)
    {
        PropertyName = propertyName;
        TargetType = targetType;
        IsNullable = isNullable;
    }
}
