// <auto-generated />
// Generated by Terminal.Gui.MetadataExtractor
// Generated at: 2026-03-03 23:20:25

#nullable enable

using System.Collections.Generic;

namespace Terminal.Gui.XamlLike;

/// <summary>
/// Information about a Terminal.Gui control type
/// </summary>
public class ControlMapping
{
    public string FullTypeName { get; }
    public string Namespace { get; }
    public bool IsContainer { get; }
    public string? Description { get; }

    public ControlMapping(string fullTypeName, string namespaceName, bool isContainer = false, string? description = null)
    {
        FullTypeName = fullTypeName;
        Namespace = namespaceName;
        IsContainer = isContainer;
        Description = description;
    }
}

/// <summary>
/// Information about an event mapping
/// </summary>
public class EventMapping
{
    public string EventName { get; }
    public string DelegateType { get; }
    public string Description { get; }
    public bool IsObsolete { get; }
    public string? ReplacementEvent { get; }

    public EventMapping(string eventName, string delegateType, string description, bool isObsolete = false, string? replacementEvent = null)
    {
        EventName = eventName;
        DelegateType = delegateType;
        Description = description;
        IsObsolete = isObsolete;
        ReplacementEvent = replacementEvent;
    }

    /// <summary>
    /// Gets the obsolete message if this event is obsolete
    /// </summary>
    public string? GetObsoleteMessage() => IsObsolete && ReplacementEvent != null
        ? $"Use '{ReplacementEvent}' instead"
        : null;
}

/// <summary>
/// Information about a TwoWay bindable property
/// </summary>
public class TwoWayBinding
{
    public string PropertyName { get; }
    public string ChangeEventName { get; }
    public string Description { get; }

    public TwoWayBinding(string propertyName, string changeEventName, string description)
    {
        PropertyName = propertyName;
        ChangeEventName = changeEventName;
        Description = description;
    }
}

/// <summary>
/// Information about a property mapping
/// </summary>
public class PropertyMapping
{
    public string PropertyName { get; }
    public string TargetType { get; }
    public string Description { get; }

    public PropertyMapping(string propertyName, string targetType, string description)
    {
        PropertyName = propertyName;
        TargetType = targetType;
        Description = description;
    }
}
